<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework><LangVersion>latest</LangVersion>
    <AssemblyName>NuclearOption.AMRAAM</AssemblyName><AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression"><HintPath>../../NuclearOption_Data/Managed/System.IO.Compression.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>../../BepInEx/core/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../../BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>../../NuclearOption_Data/Managed/Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mirage"><HintPath>../../NuclearOption_Data/Managed/Mirage.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.JSONSerializeModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.ScreenCaptureModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>../../NuclearOption_Data/Managed/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>../../NuclearOption_Data/Managed/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup><Compile Remove="tests/**/*.cs" /></ItemGroup>
</Project>
