<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>FireControlLogic</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <StartupObject>Aaa</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Aaa.cs" />
  </ItemGroup>
</Project>
