"""Generate the ship-type roster Lua table from Multiverse's own blueprint data.

Hyperspace's metaVariables map persists (name -> int) pairs fine, but Lua cannot
iterate it and ship blueprints are not enumerable from Lua either. So we ship the
list of ship type names, and probe the map by name on load.
"""
import zipfile, re, sys

src, out = sys.argv[1], sys.argv[2]
z = zipfile.ZipFile(src)

names = set()
for n in z.namelist():
    if not (n.endswith('.xml') or n.endswith('.append')):
        continue
    try:
        d = z.read(n).decode('utf-8', errors='replace')
    except Exception:
        continue
    names.update(re.findall(r'<shipBlueprint\s+[^>]*name="([^"]+)"', d))

names = sorted(names)
# Guard: keys go into a save file, so reject anything with characters that would
# make the persisted key ambiguous or unreadable.
clean = [n for n in names if re.fullmatch(r'[A-Za-z0-9_.\-]+', n)]
skipped = [n for n in names if n not in set(clean)]

with open(out, 'w', encoding='utf-8') as f:
    f.write("-- GENERATED by gen_roster.py -- do not edit by hand.\n")
    f.write("-- Ship type names extracted from Multiverse's blueprint data.\n")
    f.write("-- Used to probe metaVariables on load, since that map cannot be iterated.\n\n")
    f.write("mods = mods or {}\n")
    f.write("mods.killtracker = mods.killtracker or {}\n")
    f.write("mods.killtracker.knownShips = {\n")
    for n in clean:
        f.write('\t"%s",\n' % n)
    f.write("}\n")

print("ship types written:", len(clean))
if skipped:
    print("skipped (odd characters):", len(skipped), skipped[:5])
print("->", out)
